baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

title: Jawed Salim
description: >- # this means to ignore newlines until "baseurl:"
  Hi, I'm Jawed Salim.
  A Senior DevOps Engineer @ StackExpress (APYL Software and Systems Ltd.) Noida (India)
  Kubernetes | Terraform | AWS | Ansible | Docker | Python

#################### Comment Section (Disqus) ################
disqus_shortname: "jawed" # Add your shortname for Disqus Comment. For example : mr-brown

# Scss Directory
sass:
  sass_dir: assets/scss
  style: compressed

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-feed

paginate: 6
paginate_path: "/page/:num"

# include
include:
  - _pages
  - _authors

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

  - scope:
      path: '_authors'
    values:
      permalink: /author/:basename:output_ext
      layout: author

  - scope:
      path: ''
      type: "posts"
    values:
      permalink: post/:title:output_ext
      layout: post

  - scope:
      path: ''
      type: tags
    values:
      layout: tag

# Tags
tag_page_dir:         tag
tag_page_layout:      tags
tag_permalink_style:  pretty


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
