########################### Navigation ###################################
menu:
  # main menu
  main:
  - {name: Home, url: '/', icon: 'fa-solid fa-house'}
  - {name: About, url: '/about', icon: 'fa-solid fa-user-tie'}
  - {name: Articles, url: '/articles', icon: 'fa-solid fa-list-ul'}
  - {name: Contact, url: '/contact', icon: 'fa-solid fa-envelope'}
  # - {name: Tools, url: '/tools', icon: 'fa-solid fa-pen'}

##### Dropdown menu ######

  # - name: dropdown
  #   submenu:
  #   - name : "d1"
  #     url : "#"
  #   - name : "d2"
  #     url : "#"

##########################

  # # Footer menu
  # footer:
  # - {name: Home, url: '/'}
  # - {name: Contact, url: '/contact'}
  # - {name: Tools, url: '/tools'}


######################### Default Parameters ###########################

# logo
logo : "/assets/images/logo.png"
# meta data
author : "Jawed Salim"
description : "DevOps Engineer | Kubernetes | Terraform | AWS | Ansible | Docker | Python"
# google analitycs ID
google_analitycs_id : "" # your id
# contact form action
contact_form_action : "https://app.headlessforms.cloud/api/v1/form-submission/uDQ0nMpV8n" # contact form works with : https://formspree.io
# copyright
copyright : "Copyright &copy; 2022 Jawed Salim. Developed by [Getjekyllthemes](https://getjekyllthemes.com)"

# preloader
preloader:
  enable : true
  preloader : "" # use png, jpg, svg or gif format

# search
search:
  enable : true

############################## Social Site ##########################
social:
  - name : "linkedin"
    icon : "ti-linkedin" # themify icon pack https://themify.me/themify-icons
    link : "https://www.linkedin.com/in/j4w3d/"

  - name : "github"
    icon : "ti-github" # themify icon pack https://themify.me/themify-icons
    link : "https://github.com/heyjawed"

  - name : "gmail"
    icon : "ti-google" # themify icon pack https://themify.me/themify-icons
    link : "mailto:jawed.eternal@gmail.com"

  - name : "twitter"
    icon : "ti-twitter-alt" # themify icon pack https://themify.me/themify-icons
    link : "https://twitter.com/jawedsalim10"


